name: eshop
description: A new Flutter project.

publish_to: "none"

#version: 4.4.4+22
version: 1.0.0+1

environment:
  #sdk: ">=3.3.0 <4.0.0"
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.0.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.0
  jaguar_jwt: ^3.0.0
  flutter_local_notifications: ^19.0.0
  path_provider: ^2.1.2
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.15.0
  sms_autofill:
    git:
      url: https://github.com/jaumard/sms_autofill
  # google_maps_flutter: ^2.6.1
  google_maps_flutter: ^2.2.2
  geolocator: ^13.0.2
  file_picker: ^10.0.0
  shimmer: ^3.0.0
  geocoding: ^3.0.0
  razorpay_flutter: ^1.4.0
  #flutter_paystack: ^1.0.7
  flutter_html_to_pdf:
    git:
      url: https://github.com/mohammadhprp/flutter_html_to_pdf2
  permission_handler: ^11.2.0
  in_app_review: ^2.0.10
  open_filex: ^4.4.0
  provider: ^6.1.1
  video_player: ^2.8.2
  flutter_svg: ^2.0.16
  paytmpayments_allinonesdk: ^1.0.3
  youtube_player_flutter: ^9.1.1
  share_plus: ^10.1.2
  package_info_plus: ^8.1.1
  url_launcher: ^6.3.1
  version: ^3.0.2
  flutter_downloader: ^1.12.0
  tuple: ^2.0.2
  bottom_bar: ^2.0.3
  sqflite: ^2.3.2
  webview_flutter: ^4.10.0
  flutter_stripe: ^11.3.0
  lottie: ^3.1.3
  flutter_styled_toast: ^2.2.1
  fluttertoast: ^8.2.12
  my_fatoorah: ^3.5.0
  intl_phone_field: ^3.2.0
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.3
  flutter_widget_from_html: ^0.16.0
  phonepe_payment_sdk: ^2.0.1
  uuid: ^4.3.3
  device_info_plus: ^11.1.1
  image_cropper: ^9.0.0
  external_path: ^2.0.2
  dio: ^5.7.0
  flutter_bloc: ^9.1.0
  rename: ^3.0.2
  change_app_package_name: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  app_links: ^6.1.1
  chewie: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_code_metrics: ^5.6.0

dependency_overrides:
  intl: ^0.18.1
  http:
  speech_to_text:
    git:
      url: https://github.com/csdcorp/speech_to_text.git
      path: speech_to_text # <-- IMPORTANT: must include this!
      ref: main
  #chewie:
  #  git:
  #   url: https://github.com/mdeimert/chewie.git
  #    ref: master
  flutter_paystack:
    git:
      url: https://github.com/I-driod/flutter_paystack.git
      ref: master

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/eShop.db
    - assets/animation/maintenance.json
    - lib/Language/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf
